### ISSUE TITLE
[Bug] incorrect converting with typing shift-enter then bullet list 

### ISSUE THREAD

**Issue by bofeng** [Milkdown/milkdown#1158] opened 2023-11-06 16:29 UTC
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.1

### Steps to reproduce

1, type any character in the first line, for example, "hello"
2, type "shift-enter", the cursor will move to next line
3, type star *, followed by a space then any letter, like "a"

at the time after typing "a", the whole line `* a` immediately disappeared, and an extra `\` is shown after "hello", like `hello\`. You can reproduce this in the [playground](https://milkdown.dev/playground)

### Expected behavior

after typing the "shift-enter" and `* a`, it should keep the `* a`, like
```
hello
* a
```

### Actual behavior

after type "a", the whole "* a" line is gone, it becomes `hello\`

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment] 2023-11-08 10:58
It's a bug caused by inline sync plugin. I'll fix it. You can type a `\` character before the emphasis for a temporary solution.

```md
hello
\* a
```

**Comment by Saul-Mirone** [comment] 2023-12-11 06:03
Fixed by https://github.com/Milkdown/milkdown/pull/1171

**Closed by Saul-Mirone** 2023-12-11 06:03 UTC
Labels: bug, planned
