### ISSUE TITLE
[Feature] native browser/platform support

### ISSUE THREAD

**Issue by 43081j** [Milkdown/milkdown#246] opened 2021-12-26 15:09 UTC
Given that this is solely a project to be used inside browsers, i was hoping it would work out of the box in a browser, but it doesn't seem to.

Your demos work presumably because they're all configured to go through parcel first (i.e. a bundler).

It would be great if this worked out of the box in browsers. ProseMirror does exactly this and works fine.

It looks like unifiedjs is the one at fault here. they moved to ESM but still depend on node-only APIs, thus being useless in a browser. From what i can see, you rely on them for the AST, so im not too sure of the solution here.

This would open the door to things like a milkdown web component without a bundler, etc.

edit:

it seems like unified do provide browser equivalents of the node-only apis they depend on, but in package.json metadata only bundlers would read. maybe there's nothing for us to do here since its entirely on unified for relying on node-only APIs

**Comment by ChristianMurphy** [comment] 2022-01-05 23:43
As noted in https://github.com/vfile/vfile/issues/71 when it comes to native use in browser with import maps. Milkdown, Unified, and VFile are not blockers to native use in the browser.

The import map can be pointed to an ESM compatible CDN like https://skypack.dev, https://esm.sh, etc.

Or, a CDN which does not offer such guarantees (like https://unpkg.com) can be leveraged, by pointing any CJS based packages to an ESM based alternative in the import map where needed.

**Comment by Saul-Mirone** [comment] 2022-01-22 04:54
> looking at this again, im lost as to where i had problems 🤦 because trying again on a quick codepen POC, it seems to get past that point
> 
> this example:
> 
> ```ts
> import { defaultValueCtx, Editor } from "https://cdn.skypack.dev/@milkdown/core";
> import { nord } from "https://cdn.skypack.dev/@milkdown/theme-nord";
> import { commonmark } from "https://cdn.skypack.dev/@milkdown/preset-commonmark";
> 
> Editor.make()
>   .config((ctx) => {
>     ctx.set(defaultValueCtx, "# Testing 1234");
>   })
>   .use(nord)
>   .use(commonmark)
>   .create();
> ```
> 
> _almost_ works in the browser as-is (although remember skypack does a lot of magic, it isn't the code as is in NPM directly). the only problem seems to be this error:
> 
> ```
> Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
> ```
> 
> which i guess may be some weirdness with resolution on this particular cdn
> 
> edit:
> 
> without skypack's magic (i.e. a bundler), it does not work after all due to some commonjs-only dependencies. i've opened [vfile/vfile#71](https://github.com/vfile/vfile/issues/71) for one of them

This is caused by the `prosmierror-model` is packaged multiple times, I guess the skypack will auto bundle the dependencies for the package. So nearly all of the milkdown packages has the `@milkdown/prose` as the dependency, and it was packaged many times in different packages.

I have no idea how we can provide a packaged version as a library instead of package all dependencies in the app level. Because the prosemirror and emotion/css all need to be singleton. I think we need some help from person how have experience in this.

**Comment by duhaime** [comment] 2022-02-05 14:00
@43081j have you tried codesandbox? Why don't you want a local build system?

**Comment by 43081j** [comment] 2022-02-05 18:09
i've had a lot of difficulty explaining this problem in the various issues/discussions so have been taking a break from it.

anyhow, it isn't about me not wanting a local build, i don't even have a project im using this in. 

im just advocating for packages publishing native browser support, such that people can use them in a browser regardless of their choice of tooling. the answers i've got back have been "use a bundler and it all works", but the whole point is that you shouldn't need to use a specific toolset to consume a package (in most cases).

this package doesn't work natively in browsers, because none of the vfile packages work in a browser natively. this is because the vfile packages ship commonjs modules, which obviously will never work in a browser (since `module.exports` isn't a thing in browsers). but i've had trouble raising that issue, as the response has been "yeah but you can transform them at build time and then they will work".

which basically comes to the same point: that means the package relies on consumers using a specific toolset rather than "just working".

the discussion wasn't going anywhere and i had no support in explaining the problem any better than i could myself, so i guess we can leave this issue as "probably never being fixed".

**Comment by Saul-Mirone** [comment] 2022-02-05 18:36
Don't be so upset, I agree that we do want the packages can work just in browser without a bundler. But I maintain this project using my part time and didn't get paid for it most of the time. So it'll take time to make everything right, and it needs everyone's effort, that's how open source works. Anyway, I'm just a man, not facebook or microsoft.

**Comment by 43081j** [comment] 2022-02-05 20:33
Yes of course. That it why I raised the problem with vfile since it is theirs to solve, not only yours. But the idea was quickly shot down and discussions deteriorated. Maybe because I didn't explain well enough

**Comment by ChristianMurphy** [comment] 2022-02-05 21:40
To clarify a few things, which are being misrepresented.
Unified and VFile are not against direct use in browsers, or for requiring a build tool.

The core of the push back is that the proposed solution, import maps, does not solve the problems represented: native browser support without a build tool.
1. import maps are not natively supported in browsers nor is it is not a web standard yet. It is a proposed standard which does not yet have the [buy-in or support to become a full standard](https://chromestatus.com/feature/5315286962012160) and is only experimentally [supported in a few browsers](](https://caniuse.com/import-maps).
2. import maps are designed to be generated by a build tool, especially in a scenario like pulling from npm where the dependency chain is large and complex.

> That it why I raised the problem with vfile since it is theirs to solve

Remark, Unified, and VFile already are ESM, the package in question which is still CJS `is-buffer`.
It continues to be confusing why issues are being opened everywhere except at the root of where the CJS is coming from.

**Comment by Saul-Mirone** [comment] 2022-02-06 05:45
Maybe I can gather the call to `remark` package and it's dependencies into the `@milkdown/transformer`, then I can bundle them into ESM at there. Will give it a try when I have time.

**Comment by ChristianMurphy** [comment] 2022-02-06 13:37
> I can gather the call to remark package and it's dependencies into the @milkdown/transformer, then I can bundle them into ESM at there

It is an option, some practical considerations to pre-bundling:
1. pre-bundling would freeze the versions of remark/unified/vfile which were previously version ranges, people would be unable to get updates of these without also needing a new release of milkdown
2. for users who also use remark/unified/vfile elsewhere on their site, pre-bundling would remove build tools' ability to de-duplicate dependencies, and they would end up with two copies of all bundled dependencies on their site.
3. IANAL TINLA, most open source licenses, including the MIT license used by many projects on npm, have a notice clause (E.G. MIT's `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`) usually the burden of meeting this cause is passed to the adopter by npm, however pre-bundling includes of copy of the software directly in milkdown, and means milkdown itself would also need to generate a notice file to keep inline the the terms.

**Comment by 43081j** [comment] 2022-02-06 15:23
> This can be mostly solved with [Skypack](https://www.skypack.dev/) or [Snowpack](https://www.snowpack.dev/).
> Which are build tools, but are not bundlers

rollup behind the scenes, these are bundlers. which is why no other CDN works with vfile, only skypack because it passes the sources through rollup every time.

> The core of the push back is that the proposed solution, import maps

nobody proposed solving anything with import maps. i used import maps in my example because i didn't want to write the full import path every time. remove them and use the full path, you'll get the same problem.

> Remark, Unified, and VFile already are ESM, the package in question which is still CJS is-buffer.

true they are, but they depend on commonjs packages. which throws that effort away.

that is why this problem is vfile's, milkdown's and primarily is-buffer's (which arguably is clutter anyway, you could write code to do the same thing yourself and it'd be smaller).

**Comment by ChristianMurphy** [comment] 2022-02-06 15:58
> rollup behind the scenes, these are bundlers. which is why no other CDN works with vfile, only skypack because it passes the sources through rollup every time.

It uses rollup to resolve node specifiers, it does not bundle the code, it transforms node specifiers to url specifiers.

> remove them and use the full path, you'll get the same problem.

Right, even if `is-buffer` was native ESM or dropped entirely, it would not work natively in the browser without a build tool, due to differing specifiers.
Which is unfortunate, I hope this will change in the future, but is the reality of the JavaScript ecosystem right now.

**Comment by 43081j** [comment] 2022-02-06 16:36
> It uses rollup to resolve node specifiers, it does not bundle the code, it transforms node specifiers to url specifiers

not true.

Actual shipped source (which is on npm as-is):
https://cdn.jsdelivr.net/npm/is-buffer

skypack source (which was passed through rollup and converted to ESM on the fly):
https://cdn.skypack.dev/-/is-buffer@v2.0.5-pEqX5mY5KE8OTGseAfDW/dist=es2019,mode=imports/optimized/is-buffer.js

this is the sole reason vfile works via skypack but no other CDN.

> Right, even if is-buffer was native ESM or dropped entirely, it would not work natively in the browser without a build tool, due to differing specifiers.

The tiny amount of code that is-buffer contains would work fine in a browser, if only it was ESM.

If you're talking about the fact it'd be imported with a bare specifier, thats not your job to care about, it is the consumer's.

i think thats where the friction from you is here.

if i as a consumer want to support bare specifiers in the browser, it is my problem to solve (whether its via a bundler, import maps or any other possible solution).

**Comment by ChristianMurphy** [comment] 2022-02-06 17:18
> not true, it uses a lot more of rollup than just module resolution.

It can do more, yes, it can also leverage rollup plugins to do additional transformation if wanted.
It still does not bundle.

> if i as a consumer want to support bare specifiers in the browser, it is my problem to solve (whether its via a bundler, import maps or any other possible solution). milkdown, is-buffer and vfile are not responsible for how consumers choose to solve that problem, and therefore shouldn't be restricting them to a specific solution .

VFile hasn't constrained the solution.
There are bundlers, import map solutions, and build tools which work fine.
These have been expanded on at length here and in https://github.com/vfile/vfile/issues/71

Choosing to use tools and CDNs which have issues and are broken is purely an adopter choice, and one you seemly insist on making.
If you are unhappy with the how a CDN is handling files, raise an issue with the CDN.
If you have an issue with how `is-buffer` is packaged, raise it with `is-buffer`.

Please stop harassing tangentially related projects with self made problems.
We're people too, people who have given high quality software free of charge.
It is frustrating to deal with a person trolling for a [solution to a problem they don't even have](https://github.com/Saul-Mirone/milkdown/issues/246#issuecomment-1030671970) and [proposing a solution that wouldn't solve the stated problems if it was applied](https://github.com/Saul-Mirone/milkdown/issues/246#issuecomment-1030703535).

**Comment by 43081j** [comment] 2022-02-06 17:31
ok i need to be clearer then. it _does_ bundle in that skypack literally uses a bundler behind the scenes (rollup).

i am not saying it creates _a_ bundle, but it does most certainly use a bundler.

we just had differing definitions.

> VFile hasn't constrained the solution

vfile ships commonjs, which constrains consumers to using transforms to turn the broken (in browsers) commonjs into valid code. 

for example, rollup's commonjs plugin.

in order for vfile to remove this constraint (since its most definitely not vfile's responsibility to decide what tooling we use), it would have to ship working browser code (which it doesn't right now).

> CDNs which have issues

None of those CDNs have issues, skypack is special in that it passes everything through a bundler beforehand. This results in commonjs being turned into working code on-the-fly, which few if any other CDN does.

That is a proprietary feature of skypack, it is not a limitation or bug of all other CDNs.

> If you are unhappy with the how a CDN is handling files, raise an issue with the CDN.

all other CDNs? of course not. skypack is unique here in that it chose to solve the problem for the consumer by running all code through a transformer/bundler beforehand. no other CDN does this that im aware of (or very few do).

> Please stop harassing tangentially related projects with self made problems.

please don't turn these issues into attacks on me again. you say im harassing people here, and choose to call me names in related issues.

this isn't about me, i am advocating for this package and many others to start supporting browsers. is-buffer does not support browsers, therefore file does not support browsers, therefore milkdown does not support browsers. 

its incredibly insulting to keep resorting to personal attacks in these issues rather than trying to learn whatever it is you're missing. i am trying all i can to explain this to you but you still struggle to grasp the concept. with none of the lurkers helping me out, im unsure how i can explain any better.

it drills down to:
* commonjs is broken code in browers, it obviously is invalid and won't work
* is-buffer does not work in a browser, it is commonjs
* vfile depends on is-buffer, it does not work in a browser
* milkdown depends on vfile, it does not work in a browser

The response to this isn't "yeah but use this proprietary CDN over here and it works!" - it is to help us all contribute in the right direction to get this chain of packages to a place where they _do_ work in a browser.

i am happy to open a PR to vfile to drop that dependency, but i feel like at this rate i'll just be attacked again.

you really haven't made it easy to discuss this problem, not at all.

**Comment by admwx7** [comment] 2022-02-06 18:20
+1 on migration to native ESM support

#### Background
I'm regularly in conversations on lifting downstream restrictions on consumers; forcing consumption through non-native means would fit into that category. Additionally many of the teams I work with cannot rely on CDNs for security reasons. The choice of framework / libraries / bundlers (or lack of) is dependent completely on the downstream team and what fits their use-case best.

#### Problem / Ask
I believe @43081j is asking to drop the CJS export / import syntax for ESM; which is natively supported across the board and can be back-filled for legacy support via bundlers (for those that need to support really old browsers).


#### Question
@ChristianMurphy can you see a blocker to changing the export syntax on the referenced projects outside of time (will come back to this one)?

**Comment by ChristianMurphy** [comment] 2022-02-06 18:35
> That is a proprietary feature of skypack, it is not a limitation or bug of all other CDNs.

For CDN which are serving npm packages directly to browser, it is absolutely a limitation.
A majority of the Node ecosystem is still CJS https://twitter.com/wooorm/status/1488133593218097160, that is changing, and I hope it continues to change, but in the meantime CDNs which don't attempt to resolve CJS to ESM will continue to be limited in their function.

> commonjs is broken code in browsers, it obviously is invalid and won't work
  
It is false, commonjs worked in browsers long before ESM came around, and it can still be used in browser with appropriate libraries.
CJS is not ideal and less native, built ESM is a better alternative, but CJS is not "broken", "invalid", or "won't work".

> is-buffer, ..., it is commonjs

And yet, in the dependency chain, it continues to be the one place you haven't reached out to the maintainer to seek a resolution.
Which is at best misguided, and given the repeated suggestions to have been ignored, seems to be an intentional troll move.

> The response to this isn't "yeah but use this proprietary CDN over here and it works!"

All CDNs are to varying degrees proprietary.
The core of skypack, snowpack is open source.
As is the core of other CDNs like unpkg.

> These were a mistake to write. i can't even fathom why someone would ever claim that i 'attack' projects or any of these awfully harsh words.

They are accurate given your behavior in vfile and repeated here.
Misleading on what browsers can do and blaming tangential projects could be ignorance at first, but when repeated with increasing vigor and volume after knowing so becomes malicious.

> forcing consumption through non-native means would fit into that category

Can you expand on what you mean by this?
As noted in https://github.com/Saul-Mirone/milkdown/issues/246#issuecomment-1030703535
AFAIK there isn't a true native solution at the moment, nor have any of the discussions thus far offered a true native solution.

> I believe @43081j is asking to drop the CJS export / import syntax for ESM; which is natively supported across the board and can be back-filled for legacy support via bundlers (for those that need to support really old browsers).

Yes, and as stated in several places.
The CJS export is coming from `is-buffer` not vfile or milkdown.

> @ChristianMurphy can you see a blocker to changing the export syntax on the referenced projects outside of time (will come back to this one)?

I am not currently aware of one, but the question should be addressed to the owner of `is-buffer` directly.

**Comment by 43081j** [comment] 2022-02-06 19:03
> For CDN which are serving npm packages directly to browser, it is absolutely a limitation.

A limitation solved by people shipping ESM rather than CJS. This isn't the CDN's problem to solve.

> commonjs worked in browsers long before ESM came around

`module.exports` hasn't ever existed in browsers. i guess you're talking about using tooling to transform it into working code again? this is what i meant by "broken code" (broken may be too harsh a word though).

> the one place you haven't reached out to the maintainer to seek a resolution

That is true, because my solution would be to drop that dependency rather than update it (which i am willing to do a PR for).

---

I suggest we reset here, since the personal comments need to go away and this has become less focused than it should be.

So here's an example setup:

* Take milkdown's "getting started" example and drop the CSS import (since that'd require a bundler)

```ts
import { defaultValueCtx, Editor } from "@milkdown/core";
import { nord } from "@milkdown/theme-nord";
import { commonmark } from "@milkdown/preset-commonmark";
import { emoji } from "@milkdown/plugin-emoji";

Editor.make()
  .config((ctx) => {
    ctx.set(defaultValueCtx, "# Milkdown :heartpulse: Vanilla");
  })
  .use(nord)
  .use(commonmark)
  .use(emoji)
  .create();
```

* Install web-dev-server with `npm i -D @web/dev-server`
* Launch it with `npx web-dev-server --node-resolve`

Now we can observe that it fails straight away:

> Error while transforming node_modules/vfile/lib/minpath.js: Could not resolve import "path".
> Error while transforming node_modules/vfile/lib/minproc.js: Could not resolve import "process".
> Error while transforming node_modules/vfile/lib/minurl.js: Could not resolve import "url".

So this is an improvement we could make to vfile, @ChristianMurphy to add a package.json `exports` field. right now you have a `browser` field which bundlers will read, but node now supports the more standard `exports` field. if we specify that too, the resolution here will work and will resolve `minpath.browser.js` instead, etc.

If i then get that resolution working right, we then encounter this error:

> Uncaught SyntaxError: The requested module './../../is-buffer/index.js' does not provide an export named 'default'

This is because is-buffer is a CJS module, and `module.exports` isn't a thing in browsers.

This isn't an uncommon setup. Without any fixes, we would have to install a few plugins to get rollup's commonjs -> esm plugin running and transforming this file for us.

milkdown can't realistically ever move from vfile and co, so the only way this gets fixed is if we replace or update is-buffer. does that make more sense now @ChristianMurphy ?

All the tangential stuff doesn't really matter. This is the use case. If you don't ever intend on supporting this use case, thats unfortunate but at least we have an answer.

**Comment by admwx7** [comment] 2022-02-06 19:05
> AFAIK there isn't a true native solution at the moment

ES6 introduced the module spec for import/export and this is supported across all major browsers and was introduced as an experimental feature in Node v9.6; as of v13 you can end with .mjs or add { "type": "module" } to your package.json file to support .js files.
https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling

> The CJS export is coming from `is-buffer`

To link the blocker here: https://github.com/feross/is-buffer/pull/44

> the question should be addressed to the owner of `is-buffer` directly

Agreed. Visibility on the issue and pressure from downstream consumers is the most common way to get changes made.

#### Alternative
You could just drop the dependency and implement the exact same logic via
```
export function isBuffer(buffer) {
  return obj?.constructor?.isBuffer?.(buffer) ?? false;
}
export default isBuffer;
```
With the caveat that optional chaining and nullish coalescing were introduced in Node v14. Added benefit being one less dependency that might explode randomly one day and put all of your users at risk.

**Comment by ChristianMurphy** [comment] 2022-02-06 21:32
> A limitation solved by people shipping ESM rather than CJS. This isn't the CDN's problem to solve.

This is absolutely a limitation of CDNs.
They are serving the **node** package maangers modules to browsers.
Node speaks to packaging formats ESM and CJS, if they want to serve the entirety of npm they need to be able to handle both.

I agree with the ideal that all modules should be ESM, this is not the reality yet.


> So this is an improvement we could make to vfile, @ChristianMurphy to add a package.json exports field. right now you have a browser field which bundlers will read, but node now supports the more standard exports field. if we specify that too, the resolution here will work and will resolve minpath.browser.js instead, etc.

Feel free to open an issue and/or a PR

> > Uncaught SyntaxError: The requested module './../../is-buffer/index.js' does not provide an export named 'default'
>
> This is because is-buffer is a CJS module, and module.exports isn't a thing in browsers.

This is a bug in https://github.com/modernweb-dev/web
It is reading and can read cjs (E.G. https://github.com/modernweb-dev/web/pull/348), it sounds like there is a bug where it incorrectly resolves default

```js
// for
modules.exports = something;

// this import should work according to the node compatibility spec
import something from 'module-name'

// it sounds like the current implementation incorrectly expects
import * as something from 'module-name'
```

> ES6 introduced the module spec for import/export and this is supported across all major browsers and was introduced as an experimental feature in Node v9.6; as of v13 you can end with .mjs or add { "type": "module" } to your package.json file to support .js files.

Right, but browsers and node use different specifiers for modules.
Node uses bare specifiers, browsers uses urls specifiers.
So at this point in time, neither browsers nor node can directly consume the others packages, without a build/transform step.

The closest option to bridge that cap currently is the import map proposal https://wicg.github.io/import-maps/
which has a mix of interest and concerns https://chromestatus.com/feature/5315286962012160 and is supported in a sub-set of browsers currently https://caniuse.com/import-maps
And is likely to change before being finalized, if it is accepted at all.

> Native browser support (this use case)

Again, as of today, there is no native way to run node modules in a browser natively, period, including ESM.
The specifiers are incompatible, and interop on the browser side for bare specifiers is still being sorted.

> You could just drop the dependency and implement the exact same logic via

The same dependency is used is several places https://github.com/vfile/vfile/issues/71#issuecomment-1006402636 duplicating the logic seems off.

And in addition, at this point in time.
It is still unclear the precise issue being solved here to justify changing this dependency.

The arguments thus far:
* _Native browser support_, making this one ESM change wouldn't achieve this goal, node and browser specifiers are incompatible, and there isn't a standard solution for this yet.
* _CDN limitations_, can and should be solved by the CDN themselves.
* _Bugs in build tools_, should be addressed in the build tools themselves.

> With the caveat that optional chaining and nullish coalescing were introduced in Node v14.

Nullish support is something that could be discussed.
Unified as a whole has been cautious adopting new syntax which could break previous versions of node.

> Added benefit being one less dependency that might explode randomly one day and put all of your users at risk.

I appreciate the sentiment, but a one line change will not solve the security and supply chain risks that plague npm (and most package registries in general).

**Comment by 43081j** [comment] 2022-02-06 23:38
> This is absolutely a limitation of CDNs.
> They are serving the node package mangers modules to browsers.

ok this explains a lot about your disagreements in these various issues.

they are serving _the_ published package. the CDNs you speak of are NPM CDNs, serving what has been published to the NPM registry. they are absolutely nothing to do with _what_ you published to that registry. it is the sole responsibility of the maintainer to publish ESM, if they want ESM to be available.

i can see now why with your way of thinking, you'd have all these disagreements. you believe its the job of the CDN to serve ESM, not the job of the maintainer to publish it. 

> there is no native way to run node modules in a browser natively, period, including ESM

This seems to be what the rest of your comment revolves around. I do see your point of view now at least, you think code can't run in node which also works in browsers because import maps are still a proposal.

Though im sure you meant specifically modules which have bare-specifiers. Of course, dependency-less ES modules and modules which import relative paths will work just fine in browsers and node as-is.

> This is a bug in https://github.com/modernweb-dev/web

FYI no it is not a bug in WDS. it has the option to transform commonjs to ESM via a rollup plugin, but that is not enabled out of the box (intentionally). reason being, enabling it would mean you've now gone from a native browser project to one which will inevitably require code transforms (rollup) before it can work.

I'm happy i understand your view now at least. and we seem to be in agreement now on these definitions:

* Native browser support - code which runs in the browser _as is_, without any transforms.
* Transpiled/transformed browser support - code you've passed through a transform like rollup's plugins to produce native browser code

**Comment by ChristianMurphy** [comment] 2022-02-07 02:44
> i can see now why with your way of thinking, you'd have all these disagreements. you believe its the job of the CDN to serve ESM, not the job of the maintainer to publish it.

A mix of both.
I do think maintainers should publish in ESM, and CDNs should not ignore still significant part of the node ecosystem which has not yet moved over.

> you think code can't run in node which also works in browsers because import maps are still a proposal.

Right, most node modules have layers of dependencies, and something needs to bridge between the specifier formats.

And because the proposal is supported exclusively in Chromium with mixed signals from other browsers.
Being familiar with web components you may remember another time this has happened, the original web components (now branded v0) which were added then later removed because they didn't get support from other browsers.
I hope that import maps or a version of it do become a reality, but it's too early to call it browser native.

> Of course, dependency-less ES modules and modules which import relative paths will work just fine in browsers and node as-is.

Mostly yes, export maps also could come into play which could break that.
And I'd be cautious on pre-bundling things try to make project dependency-less for reasons highlighted in https://github.com/Saul-Mirone/milkdown/issues/246#issuecomment-1030834267

> I think we're stuck then. vfile won't have native browser support, so milkdown won't either.

Don't count out `is-buffer` just yet, the author has been particularly busy lately ([Feross talked a bit about that on JSParty recently](https://changelog.com/jsparty/210))
But other projects by the same author have been moving to ESM (for example https://github.com/webtorrent/webtorrent/issues/2177)

**Comment by 43081j** [comment] 2022-02-07 08:50
> I'd be cautious on pre-bundling things try to make project dependency-less

To be clear i wasn't suggesting we publish a bundle for this particular case. I was just talking about the fact not all packages out there do have dependencies.

As for the import maps POV, i do at least see where you're coming from now.

Though keep in mind, it is an increasingly common use case that import paths are resolved at build time and code is left as-is. 

That is exactly what WDS does out of the box with `--node-resolve`. It serves the original source with the import paths transformed for you.

So you're not against native browser support as long as is-buffer solves the problem (by updating to ESM) rather than you (by dropping or replacing is-buffer), it seems.

This is blocked until then, thanks for making it clearer.

**Comment by frnhr** [comment] 2022-12-07 18:20
Just my $0.02... The project looks great, but this issue is preventing me from using it in a Python / Django application. I have a working knowledge of JS and ES6 but it doesn't really extend into ESM modules, packages, import/exports, commerce, customs and law... 😎   But even if it did, I don't really feel like adding another build step to my CICD pipeline.

Watching this issue, with 🤞 

BTW, this issue seems to be perfectly aligned with this sweet snippet of copy I found around:

> The project targets to let everyone can use markdown editor in any platform, website or app, without pain.

**Comment by Saul-Mirone** [comment] 2023-02-24 12:59
Since it's 2023 and ESM is becoming the standard of the javascript modules. IMO `dependencies` in javascript should be treat as runtime dependencies and should not be bundled as part of the output file of a lib. I hope there will be some tools that can automatically generate import maps or something like that. But making a esm npm package can work out of box in browser is not what this project should be focus on.

**Closed by Saul-Mirone** 2023-02-24 12:59 UTC
Labels: enhancement, help wanted, blocked
