### ISSUE TITLE
[Bug]Press the Enter key to add a new <li> but the cursor does not move with it

### ISSUE THREAD

**Issue by ningkehua** [Milkdown/milkdown#1067] opened 2023-07-24 06:49 UTC
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.0

### Steps to reproduce

- Refer to the `ListItem` in the [official website code](https://github.com/Milkdown/website/blob/main/src/components/playground-editor/editor-component/ListItem.tsx) to override the default list.
- Without using tailwind to parse styles, define class and style myself to custom styles.
- When creating a new sequence or non-sequence list, press the Enter key to change the line, and find that the cursor behaves abnormally.

Below is my code ⬇️

![image](https://github.com/Milkdown/milkdown/assets/58503079/3eda74c2-fc07-43a6-92bf-e6114ba5a63a)

![image](https://github.com/Milkdown/milkdown/assets/58503079/efdd731e-a400-4f40-b2c9-47ebc1d924d1)

If I want the cursor to switch lines accurately, I can only rely on mouse clicks.
The following is a record of the problem. I don't know what I missed to cause this phenomenon. After all, the code is not too much ⬇️

https://github.com/Milkdown/milkdown/assets/58503079/19ff62b9-6b60-4c47-81a9-af5083b93bb5

### Expected behavior

The cursor should behave normally.
When I press the Enter key to change the line, I can successfully add a new line, and the cursor can also switch to the next line.

### Actual behavior

The cursor behaves abnormally. 
When I press the Enter key to change the line, I can successfully add a new line, but the cursor still stays on the previous line.

**Comment by Saul-Mirone** [comment] 2023-07-24 12:26
Did you import `@milkdown/prose/view/style/prosemirror.css` like this?
https://github.com/Milkdown/milkdown/blob/main/packages/theme-nord/src/index.ts#L6

**Comment by ningkehua** [comment] 2023-07-25 01:54
I put all the styles in the same file, because the style entry on my side is unique ⬇️

![image](https://github.com/Milkdown/milkdown/assets/58503079/865ba1ac-00d2-4073-80d3-1bf3e2dd5751)

![image](https://github.com/Milkdown/milkdown/assets/58503079/616db391-86e1-455e-8068-3bb44682f17a)

At that time, I built the milkdown style locally, and copied the generated css style here.
Therefore, I think the prosemirror style should have been introduced. After all, when I didn't rewrite `the default list code`, the list behaved normally.
⬇️

![image](https://github.com/Milkdown/milkdown/assets/58503079/ddeb036a-b8b6-454a-9ae1-acc4de821b1d)

**Comment by ningkehua** [comment] 2023-07-26 04:28
Is it possible that it is a bug of `Prosemirror`? 
There seems to be some related discussions on `Prosemirror`.
But if this is a bug, why doesn't the playground example have this problem :(

**Comment by Saul-Mirone** [comment] 2023-07-26 17:00
Can you provide a minimal reproduction? I think it might be caused by shadow root but I'm not sure. I can't reproduce it on my side.

**Comment by Saul-Mirone** [comment] 2023-08-12 04:45
Closing for idle, feel free to reopen if it can be reproduced.

**Closed by Saul-Mirone** 2023-08-12 04:45 UTC
Labels: bug, invalid
